// Code generated by girgen. DO NOT EDIT.

package javascriptcore

import (
	_ "runtime/cgo"
)

// #cgo pkg-config: javascriptcoregtk-4.1 webkit2gtk-4.1
// #cgo CFLAGS: -Wno-deprecated-declarations
// #include <stdlib.h>
// #include <jsc/jsc.h>
import "C"
