// Code generated by girgen. DO NOT EDIT.

package webkit2webextension

import (
	"runtime"
	"unsafe"

	"github.com/diamondburned/gotk4/pkg/core/gextras"
	coreglib "github.com/diamondburned/gotk4/pkg/core/glib"
)

// #include <stdlib.h>
// #include <glib-object.h>
// #include <webkit2/webkit-web-extension.h>
import "C"

// GType values.
var (
	GTypeDOMHTMLFontElement = coreglib.Type(C.webkit_dom_html_font_element_get_type())
)

func init() {
	coreglib.RegisterGValueMarshalers([]coreglib.TypeMarshaler{
		coreglib.TypeMarshaler{T: GTypeDOMHTMLFontElement, F: marshalDOMHTMLFontElement},
	})
}

// DOMHTMLFontElementOverrides contains methods that are overridable.
type DOMHTMLFontElementOverrides struct {
}

func defaultDOMHTMLFontElementOverrides(v *DOMHTMLFontElement) DOMHTMLFontElementOverrides {
	return DOMHTMLFontElementOverrides{}
}

type DOMHTMLFontElement struct {
	_ [0]func() // equal guard
	DOMHTMLElement
}

var (
	_ coreglib.Objector = (*DOMHTMLFontElement)(nil)
)

func init() {
	coreglib.RegisterClassInfo[*DOMHTMLFontElement, *DOMHTMLFontElementClass, DOMHTMLFontElementOverrides](
		GTypeDOMHTMLFontElement,
		initDOMHTMLFontElementClass,
		wrapDOMHTMLFontElement,
		defaultDOMHTMLFontElementOverrides,
	)
}

func initDOMHTMLFontElementClass(gclass unsafe.Pointer, overrides DOMHTMLFontElementOverrides, classInitFunc func(*DOMHTMLFontElementClass)) {
	if classInitFunc != nil {
		class := (*DOMHTMLFontElementClass)(gextras.NewStructNative(gclass))
		classInitFunc(class)
	}
}

func wrapDOMHTMLFontElement(obj *coreglib.Object) *DOMHTMLFontElement {
	return &DOMHTMLFontElement{
		DOMHTMLElement: DOMHTMLElement{
			DOMElement: DOMElement{
				DOMNode: DOMNode{
					DOMObject: DOMObject{
						Object: obj,
					},
					Object: obj,
					DOMEventTarget: DOMEventTarget{
						Object: obj,
					},
				},
			},
		},
	}
}

func marshalDOMHTMLFontElement(p uintptr) (interface{}, error) {
	return wrapDOMHTMLFontElement(coreglib.ValueFromNative(unsafe.Pointer(p)).Object()), nil
}

// Color: deprecated: Use JavaScriptCore API instead.
//
// The function returns the following values:
//
//   - utf8: #gchar.
//
func (self *DOMHTMLFontElement) Color() string {
	var _arg0 *C.WebKitDOMHTMLFontElement // out
	var _cret *C.gchar                    // in

	_arg0 = (*C.WebKitDOMHTMLFontElement)(unsafe.Pointer(coreglib.InternObject(self).Native()))

	_cret = C.webkit_dom_html_font_element_get_color(_arg0)
	runtime.KeepAlive(self)

	var _utf8 string // out

	_utf8 = C.GoString((*C.gchar)(unsafe.Pointer(_cret)))
	defer C.free(unsafe.Pointer(_cret))

	return _utf8
}

// Face: deprecated: Use JavaScriptCore API instead.
//
// The function returns the following values:
//
//   - utf8: #gchar.
//
func (self *DOMHTMLFontElement) Face() string {
	var _arg0 *C.WebKitDOMHTMLFontElement // out
	var _cret *C.gchar                    // in

	_arg0 = (*C.WebKitDOMHTMLFontElement)(unsafe.Pointer(coreglib.InternObject(self).Native()))

	_cret = C.webkit_dom_html_font_element_get_face(_arg0)
	runtime.KeepAlive(self)

	var _utf8 string // out

	_utf8 = C.GoString((*C.gchar)(unsafe.Pointer(_cret)))
	defer C.free(unsafe.Pointer(_cret))

	return _utf8
}

// Size: deprecated: Use JavaScriptCore API instead.
//
// The function returns the following values:
//
//   - utf8: #gchar.
//
func (self *DOMHTMLFontElement) Size() string {
	var _arg0 *C.WebKitDOMHTMLFontElement // out
	var _cret *C.gchar                    // in

	_arg0 = (*C.WebKitDOMHTMLFontElement)(unsafe.Pointer(coreglib.InternObject(self).Native()))

	_cret = C.webkit_dom_html_font_element_get_size(_arg0)
	runtime.KeepAlive(self)

	var _utf8 string // out

	_utf8 = C.GoString((*C.gchar)(unsafe.Pointer(_cret)))
	defer C.free(unsafe.Pointer(_cret))

	return _utf8
}

// SetColor: deprecated: Use JavaScriptCore API instead.
//
// The function takes the following parameters:
//
//   - value: #gchar.
//
func (self *DOMHTMLFontElement) SetColor(value string) {
	var _arg0 *C.WebKitDOMHTMLFontElement // out
	var _arg1 *C.gchar                    // out

	_arg0 = (*C.WebKitDOMHTMLFontElement)(unsafe.Pointer(coreglib.InternObject(self).Native()))
	_arg1 = (*C.gchar)(unsafe.Pointer(C.CString(value)))
	defer C.free(unsafe.Pointer(_arg1))

	C.webkit_dom_html_font_element_set_color(_arg0, _arg1)
	runtime.KeepAlive(self)
	runtime.KeepAlive(value)
}

// SetFace: deprecated: Use JavaScriptCore API instead.
//
// The function takes the following parameters:
//
//   - value: #gchar.
//
func (self *DOMHTMLFontElement) SetFace(value string) {
	var _arg0 *C.WebKitDOMHTMLFontElement // out
	var _arg1 *C.gchar                    // out

	_arg0 = (*C.WebKitDOMHTMLFontElement)(unsafe.Pointer(coreglib.InternObject(self).Native()))
	_arg1 = (*C.gchar)(unsafe.Pointer(C.CString(value)))
	defer C.free(unsafe.Pointer(_arg1))

	C.webkit_dom_html_font_element_set_face(_arg0, _arg1)
	runtime.KeepAlive(self)
	runtime.KeepAlive(value)
}

// SetSize: deprecated: Use JavaScriptCore API instead.
//
// The function takes the following parameters:
//
//   - value: #gchar.
//
func (self *DOMHTMLFontElement) SetSize(value string) {
	var _arg0 *C.WebKitDOMHTMLFontElement // out
	var _arg1 *C.gchar                    // out

	_arg0 = (*C.WebKitDOMHTMLFontElement)(unsafe.Pointer(coreglib.InternObject(self).Native()))
	_arg1 = (*C.gchar)(unsafe.Pointer(C.CString(value)))
	defer C.free(unsafe.Pointer(_arg1))

	C.webkit_dom_html_font_element_set_size(_arg0, _arg1)
	runtime.KeepAlive(self)
	runtime.KeepAlive(value)
}

// DOMHTMLFontElementClass: instance of this type is always passed by reference.
type DOMHTMLFontElementClass struct {
	*domhtmlFontElementClass
}

// domhtmlFontElementClass is the struct that's finalized.
type domhtmlFontElementClass struct {
	native *C.WebKitDOMHTMLFontElementClass
}

func (d *DOMHTMLFontElementClass) ParentClass() *DOMHTMLElementClass {
	valptr := &d.native.parent_class
	var _v *DOMHTMLElementClass // out
	_v = (*DOMHTMLElementClass)(gextras.NewStructNative(unsafe.Pointer(valptr)))
	return _v
}
