// Code generated by girgen. DO NOT EDIT.

package webkit2webextension

import (
	"runtime"
	"unsafe"

	"github.com/diamondburned/gotk4/pkg/core/gextras"
	coreglib "github.com/diamondburned/gotk4/pkg/core/glib"
)

// #include <stdlib.h>
// #include <glib-object.h>
// #include <webkit2/webkit-web-extension.h>
import "C"

// GType values.
var (
	GTypeDOMHTMLDListElement = coreglib.Type(C.webkit_dom_html_d_list_element_get_type())
)

func init() {
	coreglib.RegisterGValueMarshalers([]coreglib.TypeMarshaler{
		coreglib.TypeMarshaler{T: GTypeDOMHTMLDListElement, F: marshalDOMHTMLDListElement},
	})
}

// DOMHTMLDListElementOverrides contains methods that are overridable.
type DOMHTMLDListElementOverrides struct {
}

func defaultDOMHTMLDListElementOverrides(v *DOMHTMLDListElement) DOMHTMLDListElementOverrides {
	return DOMHTMLDListElementOverrides{}
}

type DOMHTMLDListElement struct {
	_ [0]func() // equal guard
	DOMHTMLElement
}

var (
	_ coreglib.Objector = (*DOMHTMLDListElement)(nil)
)

func init() {
	coreglib.RegisterClassInfo[*DOMHTMLDListElement, *DOMHTMLDListElementClass, DOMHTMLDListElementOverrides](
		GTypeDOMHTMLDListElement,
		initDOMHTMLDListElementClass,
		wrapDOMHTMLDListElement,
		defaultDOMHTMLDListElementOverrides,
	)
}

func initDOMHTMLDListElementClass(gclass unsafe.Pointer, overrides DOMHTMLDListElementOverrides, classInitFunc func(*DOMHTMLDListElementClass)) {
	if classInitFunc != nil {
		class := (*DOMHTMLDListElementClass)(gextras.NewStructNative(gclass))
		classInitFunc(class)
	}
}

func wrapDOMHTMLDListElement(obj *coreglib.Object) *DOMHTMLDListElement {
	return &DOMHTMLDListElement{
		DOMHTMLElement: DOMHTMLElement{
			DOMElement: DOMElement{
				DOMNode: DOMNode{
					DOMObject: DOMObject{
						Object: obj,
					},
					Object: obj,
					DOMEventTarget: DOMEventTarget{
						Object: obj,
					},
				},
			},
		},
	}
}

func marshalDOMHTMLDListElement(p uintptr) (interface{}, error) {
	return wrapDOMHTMLDListElement(coreglib.ValueFromNative(unsafe.Pointer(p)).Object()), nil
}

// Compact: deprecated: Use JavaScriptCore API instead.
//
// The function returns the following values:
//
//   - ok: #gboolean.
//
func (self *DOMHTMLDListElement) Compact() bool {
	var _arg0 *C.WebKitDOMHTMLDListElement // out
	var _cret C.gboolean                   // in

	_arg0 = (*C.WebKitDOMHTMLDListElement)(unsafe.Pointer(coreglib.InternObject(self).Native()))

	_cret = C.webkit_dom_html_d_list_element_get_compact(_arg0)
	runtime.KeepAlive(self)

	var _ok bool // out

	if _cret != 0 {
		_ok = true
	}

	return _ok
}

// SetCompact: deprecated: Use JavaScriptCore API instead.
//
// The function takes the following parameters:
//
//   - value: #gboolean.
//
func (self *DOMHTMLDListElement) SetCompact(value bool) {
	var _arg0 *C.WebKitDOMHTMLDListElement // out
	var _arg1 C.gboolean                   // out

	_arg0 = (*C.WebKitDOMHTMLDListElement)(unsafe.Pointer(coreglib.InternObject(self).Native()))
	if value {
		_arg1 = C.TRUE
	}

	C.webkit_dom_html_d_list_element_set_compact(_arg0, _arg1)
	runtime.KeepAlive(self)
	runtime.KeepAlive(value)
}

// DOMHTMLDListElementClass: instance of this type is always passed by
// reference.
type DOMHTMLDListElementClass struct {
	*domhtmldListElementClass
}

// domhtmldListElementClass is the struct that's finalized.
type domhtmldListElementClass struct {
	native *C.WebKitDOMHTMLDListElementClass
}

func (d *DOMHTMLDListElementClass) ParentClass() *DOMHTMLElementClass {
	valptr := &d.native.parent_class
	var _v *DOMHTMLElementClass // out
	_v = (*DOMHTMLElementClass)(gextras.NewStructNative(unsafe.Pointer(valptr)))
	return _v
}
