// Code generated by girgen. DO NOT EDIT.

package webkit2

import (
	"unsafe"

	externglib "github.com/diamondburned/gotk4/pkg/core/glib"
)

// #cgo pkg-config: webkit2gtk-4.0
// #cgo CFLAGS: -Wno-deprecated-declarations
// #include <stdlib.h>
// #include <glib-object.h>
// #include <webkit2/webkit2.h>
import "C"

func init() {
	externglib.RegisterGValueMarshalers([]externglib.TypeMarshaler{
		{T: externglib.Type(C.webkit_notification_permission_request_get_type()), F: marshalNotificationPermissionRequester},
	})
}

type NotificationPermissionRequest struct {
	*externglib.Object

	PermissionRequest
}

var (
	_ externglib.Objector = (*NotificationPermissionRequest)(nil)
)

func wrapNotificationPermissionRequest(obj *externglib.Object) *NotificationPermissionRequest {
	return &NotificationPermissionRequest{
		Object: obj,
		PermissionRequest: PermissionRequest{
			Object: obj,
		},
	}
}

func marshalNotificationPermissionRequester(p uintptr) (interface{}, error) {
	return wrapNotificationPermissionRequest(externglib.ValueFromNative(unsafe.Pointer(p)).Object()), nil
}
