// Code generated by girgen. DO NOT EDIT.

package webkit2

import (
	"unsafe"

	"github.com/diamondburned/gotk4/pkg/core/gextras"
	externglib "github.com/gotk3/gotk3/glib"
)

// #cgo pkg-config: webkit2gtk-4.0
// #cgo CFLAGS: -Wno-deprecated-declarations
// #include <glib-object.h>
// #include <webkit2/webkit2.h>
import "C"

func init() {
	externglib.RegisterGValueMarshalers([]externglib.TypeMarshaler{
		{T: externglib.Type(C.webkit_user_media_permission_request_get_type()), F: marshalUserMediaPermissionRequester},
	})
}

func UserMediaPermissionIsForAudioDevice(request *UserMediaPermissionRequest) bool {
	var _arg1 *C.WebKitUserMediaPermissionRequest // out
	var _cret C.gboolean                          // in

	_arg1 = (*C.WebKitUserMediaPermissionRequest)(unsafe.Pointer(request.Native()))

	_cret = C.webkit_user_media_permission_is_for_audio_device(_arg1)

	var _ok bool // out

	if _cret != 0 {
		_ok = true
	}

	return _ok
}

func UserMediaPermissionIsForVideoDevice(request *UserMediaPermissionRequest) bool {
	var _arg1 *C.WebKitUserMediaPermissionRequest // out
	var _cret C.gboolean                          // in

	_arg1 = (*C.WebKitUserMediaPermissionRequest)(unsafe.Pointer(request.Native()))

	_cret = C.webkit_user_media_permission_is_for_video_device(_arg1)

	var _ok bool // out

	if _cret != 0 {
		_ok = true
	}

	return _ok
}

type UserMediaPermissionRequest struct {
	*externglib.Object

	PermissionRequest
}

var _ gextras.Nativer = (*UserMediaPermissionRequest)(nil)

func wrapUserMediaPermissionRequest(obj *externglib.Object) *UserMediaPermissionRequest {
	return &UserMediaPermissionRequest{
		Object: obj,
		PermissionRequest: PermissionRequest{
			Object: obj,
		},
	}
}

func marshalUserMediaPermissionRequester(p uintptr) (interface{}, error) {
	val := C.g_value_get_object((*C.GValue)(unsafe.Pointer(p)))
	obj := externglib.Take(unsafe.Pointer(val))
	return wrapUserMediaPermissionRequest(obj), nil
}

func (*UserMediaPermissionRequest) privateUserMediaPermissionRequest() {}
