// Code generated by girgen. DO NOT EDIT.

package webkit2

import (
	"unsafe"

	coreglib "github.com/diamondburned/gotk4/pkg/core/glib"
)

// #include <stdlib.h>
// #include <webkit2/webkit2.h>
import "C"

//export _gotk4_webkit24_FaviconDatabase_ConnectFaviconChanged
func _gotk4_webkit24_FaviconDatabase_ConnectFaviconChanged(arg0 C.gpointer, arg1 *C.gchar, arg2 *C.gchar, arg3 C.guintptr) {
	var f func(pageUri, faviconUri string)
	{
		closure := coreglib.ConnectedGeneratedClosure(uintptr(arg3))
		if closure == nil {
			panic("given unknown closure user_data")
		}
		defer closure.TryRepanic()

		f = closure.Func.(func(pageUri, faviconUri string))
	}

	var _pageUri string    // out
	var _faviconUri string // out

	_pageUri = C.GoString((*C.gchar)(unsafe.Pointer(arg1)))
	_faviconUri = C.GoString((*C.gchar)(unsafe.Pointer(arg2)))

	f(_pageUri, _faviconUri)
}
