// Code generated by girgen. DO NOT EDIT.

package soup

// #include <stdlib.h>
// #include <libsoup/soup.h>
import "C"

// SESSION_ACCEPT_LANGUAGE alias for the Session:accept-language property, qv.
const SESSION_ACCEPT_LANGUAGE = "accept-language"

// SESSION_ACCEPT_LANGUAGE_AUTO alias for the Session:accept-language-auto
// property, qv.
const SESSION_ACCEPT_LANGUAGE_AUTO = "accept-language-auto"

// SESSION_SSL_STRICT alias for the Session:ssl-strict property, qv.
const SESSION_SSL_STRICT = "ssl-strict"
