// Code generated by girgen. DO NOT EDIT.

package soup

// #include <stdlib.h>
// #include <libsoup/soup.h>
import "C"

// SERVER_HTTPS_ALIASES alias for the Server:https-aliases property, qv.
const SERVER_HTTPS_ALIASES = "https-aliases"

// SERVER_HTTP_ALIASES alias for the Server:http-aliases property, qv.
const SERVER_HTTP_ALIASES = "http-aliases"
