// Code generated by girgen. DO NOT EDIT.

package soup

// #include <stdlib.h>
// #include <libsoup/soup.h>
import "C"

// SERVER_ADD_WEBSOCKET_EXTENSION alias for the Server:add-websocket-extension
// property, qv.
const SERVER_ADD_WEBSOCKET_EXTENSION = "add-websocket-extension"

// SERVER_REMOVE_WEBSOCKET_EXTENSION alias for the
// Server:remove-websocket-extension property, qv.
const SERVER_REMOVE_WEBSOCKET_EXTENSION = "remove-websocket-extension"
